**

!package.json
!bun.lock

!apps
!apps/api
!apps/api/package.json
!apps/geodataAPI
!apps/geodataAPI/package.json
!apps/web
!apps/web/**

!mobile
!mobile/package.json

!packages
!packages/**

apps/web/pki/archive
apps/web/pki/archive/**

**/node_modules
**/dist
**/.tanstack
**/.turbo
