**

!package.json
!bun.lock

!apps
!apps/api
!apps/api/**
!apps/geodataAPI
!apps/geodataAPI/package.json
!apps/web
!apps/web/package.json

!mobile
!mobile/package.json

!packages
!packages/**

**/node_modules
**/dist
**/.tanstack
**/.turbo
